language: node_js

# safelist
branches:
  only:
  - main
  - dev

services:
  - docker

before_install:
  - docker build -t challenge1997nr/node_microservice:latest . -f Dockerfile.prod

deploy:
  provider: script
  script: bash bin/docker_push
  on:
    branch: main

# TODO: Sample tests for CI
# script:
#   - npm run test