version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_HOSTNAME=db
    ports:
      - "80:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    command: ./bin/wait-for.sh db:27017 -- /app/node_modules/.bin/nodemon src/index.js
    depends_on: 
      - db

  db:
    image: mongo
    container_name: db
    restart: unless-stopped
    env_file: .env.db
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: